Repository GetStream/stream-js, pull requests merged in 2020-07, with the labels that each got.

#339 put createRedirectUrl in its own file
  src/lib/client.js
  src/lib/redirect_url.js
  webpack.config.js
Labels: enhancement

#340 unify missing api secret error
  src/lib/batch_operations.js
  src/lib/client.js
Labels: enhancement

#342 remove response.statusCode in favor of response.status
  src/lib/client.js
  test/integration/cloud/utils.js
  test/integration/common/faye_test.js
  test/unit/common/client_test.js
Labels: enhancement

#316 Release/v5
  .eslintrc.js
  .github/workflows/ci.yml
  .gitignore
  CHANGELOG.md
  README.md
  bin/postversion.sh
  bin/run-node-unit-tests.js
  bin/travis.sh
  bin/version.sh
  dotgit/hooks-wrapper
  dotgit/setup-hooks.sh
  karma.config.js
  package.json
  src/getstream.js
  src/lib/batch_operations.js
  src/lib/client.js
  src/lib/collections.js
  src/lib/errors.js
  src/lib/feed.js
  src/lib/files.js
  src/lib/images.js
  src/lib/personalization.js
  src/lib/promise.js
  src/lib/reaction.js
  src/lib/redirect_url.js
  src/lib/signing.js
  src/lib/user.js
  src/lib/utils.js
  test/README.md
  test/integration/browser/client_test.js
  test/integration/cloud/images.js
  test/integration/cloud/not_found_enrichment.js
  test/integration/cloud/reaction.js
  test/integration/cloud/utils.js
  test/integration/common/client_test.js
  test/integration/common/faye_test.js
  test/integration/node/client_test.js
  test/integration/utils/hooks.js
  test/integration/utils/index.js
  test/integration/utils/kjur.js
  test/unit/browser/client_test.js
  test/unit/browser/utils_test.js
  test/unit/common/client_test.js
  test/unit/common/feed_test.js
  test/unit/node/batch_test.js
  test/unit/node/client_test.js
  test/unit/node/collections_test.js
  test/unit/node/personalization_test.js
  test/unit/node/token_test.js
  test/unit/node/utils_test.js
  test/unit/utils/hooks.js
  types/getstream/index.d.ts
  types/getstream/testsGetstream.ts
  types/getstream/tsconfig.json
  webpack.config.js
  yarn.lock
Labels: enhancement

#350 add name export next to default export #347
  README.md
  src/getstream.js
  test/integration/cloud/utils.js
  test/integration/common/faye_test.js
  test/integration/node/client_test.js
  test/unit/browser/client_test.js
  test/unit/node/client_test.js
  test/unit/node/heroku_test.js
Labels: enhancement

#362 fix undef process #361
  src/getstream.js
Labels: bug

#363 OG Fix
  test/integration/cloud/open_graph.js
Labels: in progress
