Repository GetStream/stream-js, pull requests merged in 2020-06, with the labels that each got.

#309 Chore/bump dependencies
  karma.config.js
  package.json
  src/lib/batch_operations.js
  src/lib/client.js
  src/lib/utils.js
  test/integration/browser/client_test.js
  test/integration/cloud/files.js
  test/integration/cloud/follow_list.js
  test/integration/cloud/images.js
  test/integration/cloud/reaction.js
  test/integration/cloud/utils.js
  test/integration/common/client_test.js
  test/integration/common/faye_test.js
  test/integration/common/promise_test.js
  test/integration/node/client_test.js
  test/integration/utils/index.js
  test/unit/browser/client_test.js
  test/unit/common/client_test.js
  test/unit/common/faye_test.js
  test/unit/common/feed_test.js
  test/unit/common/jwt_test.js
  test/unit/common/utils_test.js
  test/unit/node/batch_test.js
  test/unit/node/client_test.js
  test/unit/node/collections_test.js
  test/unit/node/heroku_test.js
  test/unit/node/personalization_test.js
  test/unit/node/redirect_test.js
  test/unit/node/token_test.js
  yarn.lock
Labels: dependencies

#308 Refactor/convert to class
  .babelrc
  karma.config.js
  package-lock.json
  package.json
  src/getstream.js
  src/lib/batch_operations.js
  src/lib/client.js
  src/lib/collections.js
  src/lib/errors.js
  src/lib/feed.js
  src/lib/files.js
  src/lib/images.js
  src/lib/personalization.js
  src/lib/promise.js
  src/lib/reaction.js
  src/lib/signing.js
  src/lib/user.js
  src/lib/utils.js
  test/integration/browser/client_test.js
  test/integration/cloud/activities.js
  test/integration/cloud/collection.js
  test/integration/cloud/enrich.js
  test/integration/cloud/files.js
  test/integration/cloud/follow_list.js
  test/integration/cloud/images.js
  test/integration/cloud/not_found_enrichment.js
  test/integration/cloud/open_graph.js
  test/integration/cloud/permissions.js
  test/integration/cloud/personalized_feed.js
  test/integration/cloud/profile.js
  test/integration/cloud/reaction.js
  test/integration/cloud/to_targets.js
  test/integration/cloud/utils.js
  test/integration/common/client_test.js
  test/integration/common/faye_test.js
  test/integration/common/promise_test.js
  test/integration/node/client_test.js
  test/integration/utils/hooks.js
  test/integration/utils/index.js
  test/unit/browser/client_test.js
  test/unit/common/client_test.js
  test/unit/common/faye_test.js
  test/unit/common/feed_test.js
  test/unit/common/jwt_test.js
  test/unit/common/utils_test.js
  test/unit/node/batch_test.js
  test/unit/node/client_test.js
  test/unit/node/collections_test.js
  test/unit/node/heroku_test.js
  test/unit/node/personalization_test.js
  test/unit/node/redirect_test.js
  test/unit/node/token_test.js
  test/unit/utils/hooks.js
Labels: enhancement

#313 Chore/replace npm with yarn
  .github/workflows/ci.yml
  README.md
  bin/travis.sh
  package-lock.json
  package.json
  test/README.md
  yarn.lock
Labels: dependencies

#315 Remove callbacks
  README.md
  src/lib/batch_operations.js
  src/lib/client.js
  src/lib/collections.js
  src/lib/feed.js
  src/lib/personalization.js
  src/lib/reaction.js
  src/lib/user.js
  test/unit/common/client_test.js
  test/unit/common/feed_test.js
  test/unit/node/batch_test.js
  test/unit/node/client_test.js
  test/unit/node/collections_test.js
  test/unit/node/personalization_test.js
  types/getstream/index.d.ts
  types/getstream/testsGetstream.ts
Labels: enhancement

#319 Remove faye promise
  src/lib/batch_operations.js
  src/lib/client.js
  src/lib/promise.js
  test/integration/common/faye_test.js
  test/integration/utils/index.js
  test/unit/node/batch_test.js
Labels: enhancement

#318 fix unit test warnings
  test/unit/node/client_test.js
Labels: enhancement

#317 Fix integration tests
  bin/travis.sh
  karma.config.js
  package.json
  src/lib/client.js
  test/integration/browser/client_test.js
  test/integration/common/client_test.js
  test/integration/node/client_test.js
  test/integration/utils/hooks.js
  test/integration/utils/index.js
  test/integration/utils/kjur.js
Labels: enhancement

#324 remove client.makeSignedRequest fn
  package.json
  src/lib/batch_operations.js
  test/unit/browser/client_test.js
  test/unit/node/batch_test.js
  webpack.config.js
  yarn.lock
Labels: enhancement

#322 Add size comments for changes
  .eslintrc.js
  .github/workflows/size.yml
  src/lib/client.js
  src/lib/collections.js
  src/lib/feed.js
  src/lib/user.js
  test/integration/cloud/not_found_enrichment.js
  test/unit/node/client_test.js
Labels: dependencies, enhancement

#323 refactor upload file form data
  src/lib/files.js
  src/lib/images.js
  src/lib/utils.js
  test/unit/browser/utils_test.js
  test/unit/node/utils_test.js
Labels: enhancement

#325 Feature/axios requests #307
  karma.config.js
  package.json
  src/getstream.js
  src/lib/client.js
  test/integration/cloud/images.js
  test/integration/common/client_test.js
  test/unit/browser/client_test.js
  test/unit/common/client_test.js
  test/unit/node/client_test.js
  test/unit/utils/hooks.js
  webpack.config.js
  yarn.lock
Labels: enhancement

#328 Bug/thumbnail
  src/lib/images.js
  test/integration/cloud/images.js
  types/getstream/index.d.ts
  types/getstream/testsGetstream.ts
Labels: bug

#333 remove lodash dep
  package.json
  src/lib/utils.js
Labels: dependencies

#334 add some missing types and fix #310
  types/getstream/index.d.ts
Labels: enhancement

#331 Refactor/upload
  karma.config.js
  package.json
  src/lib/client.js
  src/lib/files.js
  src/lib/images.js
  test/integration/browser/client_test.js
  test/integration/utils/hooks.js
  test/unit/common/client_test.js
  types/getstream/index.d.ts
  types/getstream/tsconfig.json
  yarn.lock
Labels: enhancement

#336 Eslint/enforce camelcase
  .eslintrc.js
  src/lib/feed.js
  src/lib/reaction.js
  test/integration/cloud/reaction.js
  test/unit/node/collections_test.js
  types/getstream/index.d.ts
Labels: enhancement

#337 fixes #223 with undefined process.env
  src/getstream.js
Labels: bug
